AWSTemplateFormatVersion: 2010-09-09
Description: ---
    this is my new file

Parameters:
  Envorment:
     Description: select the dev/prod/qa
     Type: String
  NameOfInstance: 
     Description: Type the name of instance
     Type: String 
  KeyName: 
    Description:
      Type SSh keypair name
    Type: 'AWS::EC2::KeyPair::KeyName'  
Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName 
      ImageId: ami-0947d2ba12ee1ff75 
      InstanceType: t2.micro
      SecurityGroupIds:
        - sg-9fe63ea5
      Tags:
        - Key: Name
          Value: !Join ["",[!Ref Envorment, !Ref NameOfInstance]]