---
# CloudFormation Sections
# s3-01a-stack-hellobucket-17vjpyrkdxm6a
# <STACK_NAME>-<LOGICAL_ID>-<RANDOM_STRING>

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a S3 bucket with Default Properties

Resources:
   HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "suchita207-101"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index1.html
        ErrorDocument: error1.html
      VersioningConfiguration: 
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: '365'
            Transitions:
              - TransitionInDays: '1'
                StorageClass: GLACIER
        



      


