AWSTemplateFormatVersion: 2010-09-09
Description: simple dev ec2 creation using CF

Resources: 
  DevEC2: 
    Type: AWS::EC2::Instance
    Properties: 
      KeyName: such123
      DisableApiTermination: true
      ImageId: 'ami-0be2609ba883822ec'
      InstanceType: t2.micro
      SecurityGroupIds:
        - default
      Tags:
        - Key: Name
          Value: Dev_EC2_Server
        - Key: env
          Value: prod
  rdsDBInstance01:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20 
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      AvailabilityZone: us-east-1a
      BackupRetentionPeriod: 1
      DBInstanceIdentifier: mydbinstance
      DBName: mydatabase
           
     
      Engine: mysql
      EngineVersion: 8.0.20
       
      MasterUsername: suchita
      MasterUserPassword: suchita123
     
      PubliclyAccessible: true
      
      
      
      VPCSecurityGroups:
        - sg-003eab0049e06029a
      Tags:
        - Key: Name
          Value: DBinstance



'''
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 
      DBInstanceClass: 
      AllowMajorVersionUpgrade: true|false
      AutoMinorVersionUpgrade: true|false
      AvailabilityZone: 
      BackupRetentionPeriod: 
      CharacterSetName: 
      DBInstanceIdentifier: 
      DBName: 
      DBParameterGroupName: 
      DBSecurityGroups: 
        - db-sg-group
      DBSnapshotIdentifier: 
      DBSubnetGroupName: 
      Engine: mysql|oracle
      EngineVersion: 
      Iops: 
      KmsKeyId: 
      LicenseModel: 
      MasterUsername: 
      MasterUserPassword: 
      MultiAZ: true|false
      OptionGroupName: 
      Port: 
      PreferredBackupWindow: 
      PreferredMaintenanceWindow: 
      PubliclyAccessible: true|false
      SourceDBInstanceIdentifier: 
      StorageEncrypted: true|false
      StorageType: 
      VPCSecurityGroups:
        - vpc-sg-id
      Tags:
        - Key: keyname
          Value: value
 '''